[project]
name = "ibd-booster-hints-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "py-bitcoinkernel",
]

[tool.uv.sources]
py-bitcoinkernel = { git = "https://github.com/stickies-v/py-bitcoinkernel" }
